OrdererOrgs:
  - Name: Orderer1
    Domain: sample.com
    Specs:
      - Hostname: orderer1

PeerOrgs:
  - Name: Org1
    Domain: org1.sample.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.sample.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1


