# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_VERSION}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./../config:/etc/hyperledger/configtx

  orderer-base:
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ./../config/:/etc/hyperledger/configtx


  ca-base:
    image: hyperledger/fabric-ca:${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_TLS_ENABLED=false
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca-key.pem
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw'

  cli-base:
    image: hyperledger/fabric-tools:${FABRIC_VERSION}
    tty: true
    environment:
      - CHANNEL_NAME=mychannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli.sample.com
      - CORE_PEER_ADDRESS=peer0.org1.sample.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.sample.com/users/Admin@org1.sample.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../config:/opt/gopath/src/github.com/hyperledger/fabric/peer/configtx
      - ./../fabric/core/chaincode/shim/ext/cid:/opt/go/src/github.com/hyperledger/fabric/core/chaincode/shim/ext/cid
      - ./../fabric/core/chaincode/lib/cid:/opt/go/src/github.com/hyperledger/fabric/core/chaincode/lib/cid
      - ./../fabric/google/uuid:/opt/gopath/src/github.com/google/uuid
      - ./../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts