version: '2'

networks:
  basic:

services:
  ca.sample.com:
    container_name: ca.sample.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.sample.com
    ports:
      - 57054:7054
    volumes:
      - ./../crypto-config/peerOrganizations/org1.sample.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  orderer1.sample.com:
    container_name: orderer1.sample.com
    extends:
      file: base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
    ports:
      - 57050:7050
    volumes:
        - ./../crypto-config/ordererOrganizations/sample.com/orderers/orderer1.sample.com/msp:/var/hyperledger/orderer/msp
        - ./../crypto-config/ordererOrganizations/sample.com/orderers/orderer1.sample.com/tls:/var/hyperledger/orderer/tls
    networks:
      - basic


  peer0.org1.sample.com:
    container_name: peer0.org1.sample.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.sample.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_ADDRESS=peer0.org1.sample.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.sample.com0:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.sample.com:7051
    ports:
      - 57051:7051
      - 57053:7053
    volumes:
        - ./../crypto-config/peerOrganizations/org1.sample.com/peers/peer0.org1.sample.com/msp:/etc/hyperledger/fabric/msp
        - ./../crypto-config/peerOrganizations/org1.sample.com/peers/peer0.org1.sample.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - couchdb.sample.com0
    networks:
      - basic

  couchdb.sample.com0:
    container_name: couchdb.sample.com0
    image: hyperledger/fabric-couchdb:${THIRD_PARTY_VERSION}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 55984:5984
    networks:
      - basic

  ca2.sample.com:
    container_name: ca2.sample.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca2.sample.com
    ports:
      - 58054:7054
    volumes:
      - ./../crypto-config/peerOrganizations/org2.sample.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  peer0.org2.sample.com:
    container_name: peer0.org2.sample.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.sample.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_ADDRESS=peer0.org2.sample.com:9051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.sample.com0:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.sample.com:9051
    ports:
      - 9051:9051
      - 9053:9053
    volumes:
        - ./../crypto-config/peerOrganizations/org2.sample.com/peers/peer0.org2.sample.com/msp:/etc/hyperledger/fabric/msp
        - ./../crypto-config/peerOrganizations/org2.sample.com/peers/peer0.org2.sample.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - couchdb.sample.com0
    networks:
      - basic

  couchdb2.sample.com0:
    container_name: couchdb2.sample.com0
    image: hyperledger/fabric-couchdb:${THIRD_PARTY_VERSION}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 57984:5984
    networks:
      - basic

  cli.sample.com:  
    container_name: cli.sample.com
    extends:
      file: base.yaml
      service: cli-base
    networks:
        - basic