version: '2'

networks:
  basic:

services:
  ca.test.com:
    container_name: ca.test.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.test.com
    ports:
      - "7054:7054"
    volumes:
      - ./../crypto-config/peerOrganizations/org1.test.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  orderer1.test.com:
    container_name: orderer1.test.com
    extends:
      file: base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
    ports:
      - 7050:7050
    volumes:
        - ./../crypto-config/ordererOrganizations/test.com/orderers/orderer1.test.com/msp:/var/hyperledger/orderer/msp
        - ./../crypto-config/ordererOrganizations/test.com/orderers/orderer1.test.com/tls:/var/hyperledger/orderer/tls
    networks:
      - basic


  peer0.org1.test.com:
    container_name: peer0.org1.test.com
    image: hyperledger/fabric-peer
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.test.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.test.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.test.com0:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.test.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./../crypto-config/peerOrganizations/org1.test.com/peers/peer0.org1.test.com/msp:/etc/hyperledger/fabric/msp
        - ./../crypto-config/peerOrganizations/org1.test.com/peers/peer0.org1.test.com/tls:/etc/hyperledger/fabric/tls
    depends_on:
      - couchdb.test.com0
    networks:
      - basic

  couchdb.test.com0:
    container_name: couchdb.test.com0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - basic

  cli.test.com:  
    container_name: cli.test.com
    extends:
      file: base.yaml
      service: cli-base
    networks:
        - basic